services:
  - type: web
    name: spring-backend
    env: java
    plan: free
    buildCommand: ./mvnw package
    startCommand: java -jar target/*.jar
    rootDir: .
    envVars:
      - key: JAVA_VERSION
        value: 17