server:
  port: 30030
spring:
  datasource:
    url:  jdbc:postgresql://45.84.210.174:65432/cd2025bfp1g3
    username: testuser
    password: testuser
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto:  none
      format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
      type:
        descriptor:
          sql: trace
jwt:
  secret: xlJQSlmC4lT8HPtBY6vCf07klWfhUMmQze
  expiration: 36000000